services:
  user_service:
    build: .
    container_name: user_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - aristotle-net
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - aristotle-net
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped

volumes:
  postgresql_data:

networks:
  aristotle-net:
    driver: bridge
