namespace Aristotle.Domain.Exceptions;

/// <summary>
/// Represents a standardized error response following RFC 7807 Problem Details for HTTP APIs.
/// </summary>
public class ErrorResponse
{
    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int Status { get; init; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string Detail { get; init; } = string.Empty;


    /// <summary>
    /// Additional properties that provide more context about the error.
    /// </summary>
    public Dictionary<string, object?> Extensions { get; init; } = new();
}