name: Run Bruno Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bruno-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with full commit SHA
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}

    - name: Set environment variables
      run: |
        echo "APP_PORT=8080" >> $GITHUB_ENV
        echo "USE_SQLITE=true" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t darkdollynho/usr_svc-aristotle:latest .

    - name: Start user_service
      run: |
        docker run -d -p ${{ env.APP_PORT }}:8080 --name user_service darkdollynho/usr_svc-aristotle:latest

    - name: Wait for user_service to be ready
      env:
        APP_PORT: ${{ env.APP_PORT }}
      run: |
        echo "Waiting for user_service to be ready..."
        until $(curl --output /dev/null --silent --head --fail http://localhost:$APP_PORT/health); do
          echo "Still waiting..."
          sleep 5
        done

    - name: Run Bruno tests
      env:
        APP_PORT: ${{ env.APP_PORT }}
      run: |
        mkdir -p bruno_results
        bruno run -c bruno/UserService\ API/collection.bru -e bruno/UserService\ API/environments/local.json \
          --reporters html junit \
          --reporter-options html-export=bruno_results/report.html,junit-export=bruno_results/report.xml

    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      if: success()
      run: |
        docker push darkdollynho/usr_svc-aristotle:latest

#    - name: Upload test artifacts
#      uses: actions/upload-artifact@v
#      with:
#        name: bruno-test-results
#        path: bruno_results
