name: Run Bruno Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bruno-tests:
    runs-on: ubuntu-latest

    services:
      user_service:
        image: your-dockerhub-username/user_service:latest
        env:
          USE_SQLITE: true
          PORT: 8080
        ports:
          - 8080:8080
        options: >
          --health-cmd "curl --fail http://localhost:8080/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t darkdollynho/usr_svc-aristotle:latest .
        docker push darkdollynho/usr_svc-aristotle:latest

    - name: Checkout code with full commit SHA
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}

    - name: Set environment variables
      run: |
        echo "APP_PORT=8080" >> $GITHUB_ENV
        echo "USE_SQLITE=true" >> $GITHUB_ENV

    - name: Wait for user_service to be ready
      env:
        APP_PORT: ${{ env.APP_PORT }}
      run: |
        echo "Waiting for user_service to be ready..."
        until $(curl --output /dev/null --silent --head --fail http://localhost:$APP_PORT/health); do
          echo "Still waiting..."
          sleep 5
        done

    - name: Run Bruno tests
      env:
        APP_PORT: ${{ env.APP_PORT }}
      run: |
        mkdir -p bruno_results
        bruno run -c bruno/UserService\ API/collection.bru -e bruno/UserService\ API/environments/local.json \
          --reporters html junit \
          --reporter-options html-export=bruno_results/report.html,junit-export=bruno_results/report.xml

    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bruno-test-results
        path: bruno_results
