name: SonarQube and Tests
on:
  push:
    branches:
      - main
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: windows-latest
    env:
      CI: true
    
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
          
      - name: Install SonarQube Cloud scanner and dotnet-coverage
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
          dotnet tool install --global dotnet-coverage
      
      - name: Restore Dependencies
        run: dotnet restore Aristotle_Study.sln
      
      - name: Begin SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"mayconht_Aristotle_Study" /o:"personalprojcts" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml" /d:sonar.coverage.exclusions="**/Program.cs,**/Migrations/**/*.cs,**/*Tests.cs,**/obj/**/*.cs"
      
      - name: Build Solution
        run: dotnet build Aristotle_Study.sln --configuration Release --no-restore
      
      - name: Run Tests with Coverage Collection
        run: dotnet-coverage collect "dotnet test Aristotle_Study.sln --configuration Release --no-build" -f opencover -o "coverage.opencover.xml"
      
      - name: End SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      
      - name: Generate Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: 'coverage.opencover.xml'
          targetdir: './coveragereport'
          reporttypes: 'HtmlInline;Cobertura'
      
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport
      
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            Aristotle_Project/bin/Release/net9.0/
            Tests/bin/Release/net9.0/